### THIS WORKS WITH PYCHARM
### Send Valid Request
POST http://localhost:18080/2015-03-31/functions/function/invocations
Content-Type: application/json

{
  "rsvp_total": 2,
  "rsvp_name": "From PyCharm With Love"
}

### Send Invalid Request
POST http://localhost:18080/2015-03-31/functions/function/invocations
Content-Type: application/json

{
  "rsvp_total": 20,
  "rsvp_name": "From PyCharm With Love"
}