name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Run workflow on pushes to the main branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.8.3
          echo "Poetry installed"

      - name: Export dependencies to requirements.txt
        run: |
          poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -t src/

#      - name: Run tests
#        run: |
#          python3 -m unittest discover src

      - name: Package Lambda function
        run: |
          zip -r function.zip src/

      - name: Update Lambda Environment Variables with Supabase Secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          aws lambda update-function-configuration \
            --function-name nerdfestexpo-sanantonio-rsvp \
            --environment "Variables={SUPABASE_URL=$SUPABASE_URL,SUPABASE_KEY=$SUPABASE_KEY}" \
            --region us-west-2

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-code --function-name nerdfestexpo-sanantonio-rsvp --zip-file fileb://function.zip --region us-west-2